### ISSUE TITLE
unhandled slurm job state, KeyError: 'RD'

### ISSUE THREAD

**Issue by charlgren** [gwforg/gwf#244]
There is  a slurm job state, 'RD', which is not handled in _parse_squeue_output() in slurm.py which prevents 'gwf status' from running. Either the status should be included in SLURM_JOB_STATES, or checked as in status() and set to UNKNOWN upon failed retrieval (which would handle any other unknown state too), or maybe both.
```
userid@cluster directory$ squeue | tail -n1
           1234567      core   (null)  user_id RD       0:00      1 (Reservation g2019011_1 was deleted)
```
```
userid@cluster directory$ gwf status
Traceback (most recent call last):
  File "/home/userid/.conda/envs/env_name/bin/gwf", line 10, in <module>
    sys.exit(main())
  File "/home/userid/.conda/envs/env_name/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/userid/.conda/envs/env_name/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/userid/.conda/envs/env_name/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/userid/.conda/envs/env_name/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/userid/.conda/envs/env_name/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/userid/.conda/envs/env_name/lib/python3.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/userid/.conda/envs/env_name/lib/python3.7/site-packages/gwf/plugins/status.py", line 93, in status
    with backend_cls() as backend:
  File "/home/userid/.conda/envs/env_name/lib/python3.7/site-packages/gwf/backends/slurm.py", line 147, in __init__
    self._status = _parse_squeue_output(_call_squeue())
  File "/home/userid/.conda/envs/env_name/lib/python3.7/site-packages/gwf/backends/slurm.py", line 95, in _parse_squeue_output
    job_states[job_id] = SLURM_JOB_STATES[state]
KeyError: 'RD'
```

**Comment by dansondergaard** [comment]
Thanks for reporting this! It'll be fixed in version 1.5.1 which should be out later today.
