### ISSUE TITLE
Handling of slurm requeude jobs

### ISSUE THREAD

**Issue by madsheilskov** [gwforg/gwf#251]
I get the error below when submitting a pipeline of gwf job. The last line perhap  hints to the slurm job state code `RH REQUEUE_HOLD` . Is it possible that gwf fails when a job is requeued ?
 

`(duplexhet) [mhra@fe1 plasma6_control_N227-1151_ds_sporacrc]$ gwf -b slurm run
Traceback (most recent call last):
  File "/home/mhra/anaconda3/envs/duplexhet/bin/gwf", line 10, in <module>
    sys.exit(main())
  File "/home/mhra/anaconda3/envs/duplexhet/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/mhra/anaconda3/envs/duplexhet/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/mhra/anaconda3/envs/duplexhet/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mhra/anaconda3/envs/duplexhet/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mhra/anaconda3/envs/duplexhet/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/mhra/anaconda3/envs/duplexhet/lib/python3.6/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/mhra/anaconda3/envs/duplexhet/lib/python3.6/site-packages/gwf/plugins/run.py", line 34, in run
    with backend_cls() as backend:
  File "/home/mhra/anaconda3/envs/duplexhet/lib/python3.6/site-packages/gwf/backends/slurm.py", line 147, in __init__
    self._status = _parse_squeue_output(_call_squeue())
  File "/home/mhra/anaconda3/envs/duplexhet/lib/python3.6/site-packages/gwf/backends/slurm.py", line 95, in _parse_squeue_output
    job_states[job_id] = SLURM_JOB_STATES[state]
KeyError: 'RH'
`

**Comment by madsheilskov** [comment]
No errors after updating gwf to lastest version 1.5.

**Comment by dansondergaard** [comment]
Thanks for reporting... and closing! :)
