### ISSUE TITLE
Cancel command broken in 1.7.0

### ISSUE THREAD

**Issue by micknudsen** [gwforg/gwf#259]
I am seeing errors like this quite often. Something with the `cancel` command seems broken in `gwf 1.7.0´.

```
(moma-somatic-pipeline-develop) [michaelk@fe1 workflow]$ gwf cancel
This will cancel all targets! Do you want to continue? [y/N]: y
Cancelling target FastQC_Q14T00529D_VUD_MSK_N145_2415_S51_L001_R1_001.
scancel: Terminating job 4728169
scancel: error: Kill job error on job id 4728169: Invalid job id specified
Traceback (most recent call last):
  File "/home/michaelk/miniconda3/envs/moma-somatic-pipeline-develop/lib/python3.6/site-packages/gwf/utils.py", line 263, in func_wrapper
    return func(*args, **kwargs)
  File "/home/michaelk/miniconda3/envs/moma-somatic-pipeline-develop/lib/python3.6/site-packages/gwf/backends/slurm.py", line 97, in call_cancel_command
    return call("scancel", "--verbose", job_id)
  File "/home/michaelk/miniconda3/envs/moma-somatic-pipeline-develop/lib/python3.6/site-packages/gwf/backends/utils.py", line 34, in call
    raise BackendError(stderr)
gwf.backends.exceptions.BackendError: scancel: Terminating job 4728169
scancel: error: Kill job error on job id 4728169: Invalid job id specified

Call to call_cancel_command failed, retrying in 0 seconds.
scancel: Terminating job 4728169
scancel: error: Kill job error on job id 4728169: Invalid job id specified
Traceback (most recent call last):
  File "/home/michaelk/miniconda3/envs/moma-somatic-pipeline-develop/lib/python3.6/site-packages/gwf/utils.py", line 263, in func_wrapper
    return func(*args, **kwargs)
  File "/home/michaelk/miniconda3/envs/moma-somatic-pipeline-develop/lib/python3.6/site-packages/gwf/backends/slurm.py", line 97, in call_cancel_command
    return call("scancel", "--verbose", job_id)
  File "/home/michaelk/miniconda3/envs/moma-somatic-pipeline-develop/lib/python3.6/site-packages/gwf/backends/utils.py", line 34, in call
    raise BackendError(stderr)
gwf.backends.exceptions.BackendError: scancel: Terminating job 4728169
scancel: error: Kill job error on job id 4728169: Invalid job id specified

Call to call_cancel_command failed, retrying in 1 seconds.
scancel: Terminating job 4728169
scancel: error: Kill job error on job id 4728169: Invalid job id specified
Traceback (most recent call last):
  File "/home/michaelk/miniconda3/envs/moma-somatic-pipeline-develop/lib/python3.6/site-packages/gwf/utils.py", line 263, in func_wrapper
    return func(*args, **kwargs)
  File "/home/michaelk/miniconda3/envs/moma-somatic-pipeline-develop/lib/python3.6/site-packages/gwf/backends/slurm.py", line 97, in call_cancel_command
    return call("scancel", "--verbose", job_id)
  File "/home/michaelk/miniconda3/envs/moma-somatic-pipeline-develop/lib/python3.6/site-packages/gwf/backends/utils.py", line 34, in call
    raise BackendError(stderr)
gwf.backends.exceptions.BackendError: scancel: Terminating job 4728169
scancel: error: Kill job error on job id 4728169: Invalid job id specified

Call to call_cancel_command failed, retrying in 2 seconds.
Error: Could not cancel target
(moma-somatic-pipeline-develop) [michaelk@fe1 workflow]$ 
```

**Comment by dansondergaard** [comment]
Thanks! I'll definitely look at that first thing.
